In [1]:
import torch

In [2]:
# your journey starts with one step
torch.manual_seed(123)
inputs = torch.rand((6,3))

In [3]:
attention_scores = torch.empty(6,6)

In [4]:
for i , x1 in enumerate(inputs):
    for j , x2 in enumerate(inputs):
        attention_scores[i,j] = torch.dot(x1, x2)

In [5]:
attention_scores

tensor([[0.4179, 0.4602, 0.1397, 0.5509, 0.2036, 0.3884],
        [0.4602, 1.2304, 0.2611, 1.1189, 0.3408, 1.0023],
        [0.1397, 0.2611, 0.0630, 0.2580, 0.0887, 0.2193],
        [0.5509, 1.1189, 0.2580, 1.0992, 0.3343, 0.8977],
        [0.2036, 0.3408, 0.0887, 0.3343, 0.1445, 0.3155],
        [0.3884, 1.0023, 0.2193, 0.8977, 0.3155, 0.8600]])

In [6]:
attention_scores2=inputs @inputs.T

In [8]:
attention_scores2

tensor([[0.4179, 0.4602, 0.1397, 0.5509, 0.2036, 0.3884],
        [0.4602, 1.2304, 0.2611, 1.1189, 0.3408, 1.0023],
        [0.1397, 0.2611, 0.0630, 0.2580, 0.0887, 0.2193],
        [0.5509, 1.1189, 0.2580, 1.0992, 0.3343, 0.8977],
        [0.2036, 0.3408, 0.0887, 0.3343, 0.1445, 0.3155],
        [0.3884, 1.0023, 0.2193, 0.8977, 0.3155, 0.8600]])

In [11]:
attention_weights = torch.softmax(attention_scores2, dim=-1)

In [12]:
attention_weights

tensor([[0.1748, 0.1824, 0.1324, 0.1997, 0.1411, 0.1697],
        [0.1174, 0.2536, 0.0962, 0.2268, 0.1042, 0.2019],
        [0.1609, 0.1817, 0.1490, 0.1811, 0.1529, 0.1743],
        [0.1340, 0.2365, 0.1000, 0.2319, 0.1079, 0.1896],
        [0.1603, 0.1838, 0.1429, 0.1827, 0.1511, 0.1793],
        [0.1268, 0.2342, 0.1070, 0.2110, 0.1179, 0.2032]])

In [13]:
all_context_vectors = attention_weights @ inputs

In [14]:
all_context_vectors

tensor([[0.4193, 0.2282, 0.5486],
        [0.4762, 0.2052, 0.6228],
        [0.4063, 0.2197, 0.5424],
        [0.4690, 0.2138, 0.6075],
        [0.4097, 0.2196, 0.5476],
        [0.4572, 0.2075, 0.6049]])