In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
from pathlib import Path
import re
import tiktoken

In [2]:
def read_data(filepath: Path):
    with open(filepath, "r", encoding="utf-8") as f:
        raw_text = f.read()
    return raw_text


In [3]:
data = read_data("../resources/verdict.txt")

In [4]:
for i in range(0,10,2):
    print(i)

0
2
4
6
8


In [5]:
class GPTDatasetV1(Dataset):
    def __init__(self, text, tokeniser, max_length, stride):
        self.tokeniser = tokeniser
        self.input_ids = []
        self.target_ids=[]

        token_ids = tokeniser.encode(text,allowed_special={"<|endoftext|>"})

        for i in range(0,len(token_ids)-max_length, stride):
            input_chunk= token_ids[i:i+max_length]
            target_chunk= token_ids[i+1: i+max_length+1] 
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)
        

    def __getitem__(self,idx):
        return self.input_ids[idx], self.target_ids[idx]



In [6]:
def create_dataloader_v1(text, batch_size=4,max_length=256, stride=128, shuffle=True,drop_last=True):
    tokeniser = tiktoken.get_encoding("gpt2")
    dataset = GPTDatasetV1(text,tokeniser,max_length,stride)
    dataloader = DataLoader(dataset, batch_size=batch_size,shuffle=shuffle, drop_last=drop_last)
    return dataloader
    

In [7]:
dataloader = create_dataloader_v1(data, batch_size=2,max_length=4,stride=1, shuffle=False)

In [8]:
data_iter = iter(dataloader)
batch1 = next(data_iter)
print(batch1) #return input_token and target_token

[tensor([[  464,  4643, 11600,    25],
        [ 4643, 11600,    25,  1717]]), tensor([[ 4643, 11600,    25,  1717],
        [11600,    25,  1717,   342]])]


In [9]:
batch2 = next(data_iter)
print(batch2) #return input_token and target_token

[tensor([[11600,    25,  1717,   342],
        [   25,  1717,   342,   854]]), tensor([[   25,  1717,   342,   854],
        [ 1717,   342,   854, 41328]])]


Here, we will understand how the embedding layer is like a lookup.

In [10]:
vocab_size=5
output_dim=2
embedding_layer = nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight.shape)
print(embedding_layer.weight)

torch.Size([5, 2])
Parameter containing:
tensor([[-0.4291, -2.2476],
        [-1.1059,  0.3573],
        [ 0.2605, -0.1207],
        [-0.5372,  1.9485],
        [ 0.5412, -0.4585]], requires_grad=True)


In [11]:
embedding_layer(torch.tensor(3))

tensor([-0.5372,  1.9485], grad_fn=<EmbeddingBackward0>)

In [12]:
torch.tensor(3)

tensor(3)

In [13]:
embedding_layer(torch.tensor([1,2,3]))

tensor([[-1.1059,  0.3573],
        [ 0.2605, -0.1207],
        [-0.5372,  1.9485]], grad_fn=<EmbeddingBackward0>)

### Creating Positional Encodings

In [14]:
output_dim = 256
vocab_size = 50257
embedding_layer  = nn.Embedding(vocab_size, output_dim)

In [15]:
max_length = 4
dataloader = create_dataloader_v1(data, batch_size=8,max_length=max_length,stride=max_length, shuffle=False)

In [16]:
data_iter = iter(dataloader)

In [17]:
inputs, targets = next(data_iter)

In [18]:
print(inputs)

tensor([[  464,  4643, 11600,    25],
        [ 1717,   342,   854, 41328],
        [   25, 40417,   198,  3109],
        [ 9213,   422, 11145,   271],
        [ 1668,   319,  3267,  2310],
        [   11, 48609,   198,   198],
        [   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271]])


In [19]:
print(targets)

tensor([[ 4643, 11600,    25,  1717],
        [  342,   854, 41328,    25],
        [40417,   198,  3109,  9213],
        [  422, 11145,   271,  1668],
        [  319,  3267,  2310,    11],
        [48609,   198,   198,    40],
        [  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899]])


In [20]:
token_embeddings  = embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [21]:
# context length here is the maximum lenght of a given sentence.
context_length = max_length
pos_embedding_layer = nn.Embedding(context_length, output_dim)
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
print(pos_embeddings.shape)

torch.Size([4, 256])


In [22]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings)

tensor([[[-1.8986, -2.1099,  2.3424,  ..., -1.2420,  0.9648, -0.9894],
         [-0.6543,  0.0421, -0.3086,  ...,  1.6095,  0.7694,  0.3336],
         [ 0.8008, -0.1051,  0.6068,  ...,  2.4534,  0.4855, -1.1804],
         [-0.3418, -1.5308, -1.4341,  ..., -1.2648,  0.1561,  0.2622]],

        [[ 0.4555, -2.7119,  2.6021,  ..., -1.2263,  0.1512, -0.6984],
         [-1.8337, -1.2027,  1.2223,  ...,  1.2439, -0.1694, -0.7687],
         [ 1.8680,  1.1382, -0.9113,  ...,  1.8025,  0.9990, -1.7271],
         [ 0.8220, -0.7029,  0.8511,  ..., -0.8136,  1.0490, -0.9767]],

        [[ 0.0836, -2.7003, -0.1940,  ..., -1.5268,  0.1354, -1.3546],
         [-1.1759, -0.3684, -1.5890,  ...,  0.9603,  1.1061, -1.8884],
         [ 1.3125,  1.2845,  0.0115,  ...,  0.9693,  0.9124, -0.8834],
         [-1.1735, -0.8407, -1.4049,  ..., -1.2902,  1.1115,  0.4502]],

        ...,

        [[-0.9114, -1.1214,  0.1217,  ..., -2.8647, -0.7402, -0.2048],
         [-1.7838, -2.2258,  1.3884,  ...,  0.2678,  0.65

In [23]:
inputs = torch.tensor( [[0.43, 0.15, 0.89], [0.55, 0.87, 0.66], 
                        [0.57, 0.85, 0.64], [0.22, 0.58, 0.33], 
                        [0.77, 0.25, 0.10], [0.05, 0.80, 0.55]])

In [24]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [25]:
query = inputs[1]
print(query)

tensor([0.5500, 0.8700, 0.6600])


In [26]:
attention_scores_2 = torch.empty(inputs.shape[0])
print(attention_scores_2)

tensor([0., 0., 0., 0., 0., 0.])


In [27]:
for i, x_i in enumerate(inputs):
    attention_scores_2[i] = query @ x_i

print(attention_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [28]:
normalised_attention_scores = attention_scores_2/attention_scores_2.sum()
print(normalised_attention_scores)

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])


In [29]:
naive_softmax = lambda x: torch.exp(x)/torch.exp(x).sum()
normalised_attention_scores  = naive_softmax(attention_scores_2)
print(normalised_attention_scores)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])


In [30]:
normalised_attention_scores  = torch.softmax(attention_scores_2,dim=0)
print(normalised_attention_scores)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])


In [31]:
query = inputs[1]
context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vec_2 += normalised_attention_scores[i] * x_i

print(context_vec_2)


tensor([0.4419, 0.6515, 0.5683])


In [32]:
unormalised_attention_score = inputs @ inputs.T
print(unormalised_attention_score)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [33]:
attention_weights = torch.softmax(unormalised_attention_score,dim=0)
print(attention_weights)

tensor([[0.2098, 0.1385, 0.1390, 0.1435, 0.1526, 0.1385],
        [0.2006, 0.2379, 0.2369, 0.2074, 0.1958, 0.2184],
        [0.1981, 0.2333, 0.2326, 0.2046, 0.1975, 0.2128],
        [0.1242, 0.1240, 0.1242, 0.1462, 0.1367, 0.1420],
        [0.1220, 0.1082, 0.1108, 0.1263, 0.1879, 0.0988],
        [0.1452, 0.1581, 0.1565, 0.1720, 0.1295, 0.1896]])


In [34]:
attention_weights[:,0].sum()

tensor(1.0000)

In [35]:
context_vector = attention_weights @ inputs
print(context_vector)

tensor([[0.4017, 0.5023, 0.5059],
        [0.5595, 0.7824, 0.6953],
        [0.5538, 0.7686, 0.6834],
        [0.3369, 0.4647, 0.4119],
        [0.3525, 0.4059, 0.3657],
        [0.3856, 0.5761, 0.5077]])


Self attention with trainable weights

In [36]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2 # generally the sizes for input and output are the same but the author suggests different for better understanding.

In [37]:
print(d_in)
print(d_out)

3
2


In [38]:
w_q  =nn.Parameter(torch.rand(d_in,d_out), requires_grad=False)
w_k  =nn.Parameter(torch.rand(d_in,d_out), requires_grad=False)
w_v  =nn.Parameter(torch.rand(d_in,d_out), requires_grad=False)


In [39]:
q_2 = x_2 @ w_q
k_2 = x_2 @ w_k
v_2 = x_2 @ w_v

In [40]:
print(q_2)

tensor([0.9675, 0.8405])


In [41]:
key = inputs @ w_k 
values  = inputs @ w_v

In [42]:
print("keys: ", key)
print("#"*50)
print("values: ", values)

keys:  tensor([[1.0260, 1.0260],
        [1.3387, 1.2347],
        [1.3098, 1.2211],
        [0.7602, 0.6513],
        [0.4213, 0.6325],
        [1.0876, 0.8295]])
##################################################
values:  tensor([[0.6963, 0.4945],
        [1.0277, 1.1456],
        [1.0210, 1.1358],
        [0.5542, 0.6689],
        [0.6120, 0.6406],
        [0.6574, 0.8025]])


In [43]:
key_2 = key[1]
attention_score_22 = q_2.dot(key_2)# key_2.dot(q_2)

In [44]:
print(key_2.shape)
print(q_2.shape)
print(attention_score_22.shape)

torch.Size([2])
torch.Size([2])
torch.Size([])


In [45]:
attention_score_22

tensor(2.3329)

In [46]:
attention_score_2 = q_2 @ key.T # the second element here matches the attention_score_22

Calculating attention scores for all , but I have hurried to do this, the book first suggests we stick with q_2 and first scale and then will come back to the doing all at once.

In [47]:
#query = inputs @ w_q
#print(query.shape)
#print(key.shape)

#attention_scores = query @ key.T
#print(attention_scores.shape)

Lets calculate normalise to get from attention_scores to attention_weights for q_2 first.

In [48]:
d_k = key.shape[-1]
print(d_k)

2


In [49]:
attention_weights_2 = torch.softmax(attention_score_2/d_k**0.5, dim = -1)

In [50]:
attention_weights_2

tensor([0.1699, 0.2383, 0.2317, 0.1134, 0.0889, 0.1577])

In [51]:
attention_scores_2 @ values

tensor([5.3218, 5.7494])

Create a class for extracting the context vector

In [52]:
class SelfAttentionV1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.d_in = d_in
        self.d_out= d_out
        self.wq = nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
        self.wk = nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
        self.wv = nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
        
    def forward(self, inputs):
        query = inputs @ self.wq
        key= inputs @ self.wk
        value= inputs @ self.wv
        
        attention_score = query @ key.T
        d_k = key.shape[-1]
        attention_weights = torch.softmax(attention_score/d_k ** 0.5, dim = -1)
        context_vector = attention_weights @ value
        return context_vector


In [53]:
torch.manual_seed(123)
self_attention_v1 = SelfAttentionV1(3,2)
self_attention_v1(inputs)

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]])

In [54]:

class SelfAttentionV2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias = False):
        super().__init__()
        self.d_in = d_in
        self.d_out= d_out
        self.wq = nn.Linear(d_in,d_out, bias=qkv_bias)
        self.wk = nn.Linear(d_in,d_out, bias=qkv_bias)
        self.wv = nn.Linear(d_in,d_out, bias=qkv_bias)
        
    def forward(self, inputs):
        query = self.wq(inputs)
        key= self.wk(inputs)
        value= self.wv(inputs)
        
        attention_score = query @ key.T
        d_k = key.shape[-1]
        attention_weights = torch.softmax(attention_score/d_k ** 0.5, dim = -1)
        context_vector = attention_weights @ value
        return context_vector

In [55]:
torch.manual_seed(789)
self_attention_v2 = SelfAttentionV2(3,2)
result = self_attention_v2(inputs)
print(result)

tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)


In [56]:
wq = self_attention_v2.state_dict()["wq.weight"]
wk = self_attention_v2.state_dict()["wk.weight"]
wv = self_attention_v2.state_dict()["wv.weight"]

In [57]:
self_attention_v1.wq = nn.Parameter(wq.T)
self_attention_v1.wk = nn.Parameter(wk.T)
self_attention_v1.wv = nn.Parameter(wv.T)

# here we have take the weights from v2 and applied to v2 and we can see they are essentially doing the operations, 
# we can see outputs are the same once we copy the weight matrices.
self_attention_v1(inputs)

tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)

In [59]:
self_attention_v2.wq(inputs)

tensor([[ 0.6600, -0.2047],
        [ 0.9091, -0.4471],
        [ 0.8960, -0.4419],
        [ 0.5034, -0.2633],
        [ 0.4088, -0.2232],
        [ 0.6628, -0.3292]], grad_fn=<MmBackward0>)