In [1]:
import torch

In [2]:
# your journey starts with one step
torch.manual_seed(123)
inputs = torch.rand((6,3))

In [3]:
din=3
dout=2
wq = torch.nn.Parameter(torch.randn(din,dout),requires_grad=True)
wk = torch.nn.Parameter(torch.randn(din,dout),requires_grad=True)
wv = torch.nn.Parameter(torch.randn(din,dout),requires_grad=True)

In [4]:
# we treat journey vector as our query vector
x2 = inputs[1]
query2 = x2 @ wq
# to get context vectors we would need the keys and values across the full input
keys = inputs @ wk
values = inputs @ wv

In [5]:
print(query2.shape)
print(keys.shape)
print(values.shape)

torch.Size([2])
torch.Size([6, 2])
torch.Size([6, 2])


In [6]:
attention_score = query2 @ keys.T
print(attention_score.shape)

torch.Size([6])


In [7]:
print(attention_score)

tensor([0.1976, 0.3041, 0.1116, 0.1607, 0.3675, 0.5791],
       grad_fn=<SqueezeBackward4>)


In [8]:
# normalise attention score to get attention weights
dk = 2 # dk is embedding dimension of the model, howeveer here I have not used the embedding 
# dimension, we will used this specific parameter later 
attention_weights = torch.softmax(attention_score/(dk**0.5), dim= -1)

In [9]:
print(attention_weights)
print(attention_weights.shape)

tensor([0.1555, 0.1677, 0.1463, 0.1515, 0.1754, 0.2036],
       grad_fn=<SoftmaxBackward0>)
torch.Size([6])


In [10]:
context_vector = attention_score @ values

In [11]:
print(context_vector)

tensor([-3.1386,  0.7401], grad_fn=<SqueezeBackward4>)


In [12]:
# if we now consider the full query vector the output sizes would also change
query = inputs @ wq
print(query.shape)

torch.Size([6, 2])


In [14]:
full_attention_score = query @ keys.T

In [15]:
print(full_attention_score.shape)

torch.Size([6, 6])


In [17]:
full_attention_weights = torch.softmax(full_attention_score/(dk**0.5), dim=-1)

In [18]:
print(full_attention_weights.shape)

torch.Size([6, 6])


In [19]:
full_context = full_attention_weights @ values
print(full_context.shape)

torch.Size([6, 2])


In [20]:
print(full_context)
print(context_vector)

tensor([[-1.6836,  0.3672],
        [-1.7127,  0.3734],
        [-1.6905,  0.3618],
        [-1.6909,  0.3751],
        [-1.7109,  0.3617],
        [-1.7347,  0.3683]], grad_fn=<MmBackward0>)
tensor([-3.1386,  0.7401], grad_fn=<SqueezeBackward4>)
